#!/usr/bin/env bash
sudo apt update && sudo apt upgrade -y
sudo apt install git unzip zip htop curl -y
curl -O https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh
bash Anaconda3-2022.05-Linux-x86_64.sh -yes
# shellcheck disable=SC1090
source ~/.bashrc
conda env create -f environment.yml
