[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Pierre in Frame"
authors = [{name = "Diego Corrêa da Silva", email = "diego.correa@ufba.br"}]
dynamic = ["version", "description"]
